### ISSUE TITLE
Not a JSS-Rules-Engine question - it's more of a GraphQL question

### ISSUE THREAD

**Issue by b-rewired** [JackTheHack/Sitecore.JSS-Rule-Engine#1]
Hey there - I was hoping you could help me out a bit - I really like your solution to leveraging the Sitecore rules in the front-end. That's a lot of work you've done and I am impressed!  

So I'll preface this by saying this is not an issue with your code - it's more of a question of "how did you get this data to return"? sort of thing.

I'm trying to figure out why you are able to retrieve the "Rules" field and I am getting null.  I'm using the same GraphQL query as you are on a simple page item that has just a single component that has been personalized (it's very simple).  It's all published and the raw Layout shows the correct xml.   I get back the item name but the "field(name:"Rules") returns null.

I am running Sitecore 10.3.1 and this is not XM - but I don't think that should matter.  Did you have do anything special?

```
<r xmlns:p="p"
   xmlns:s="s"
   p:p="1">
	<d id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
		<r uid="{FE11C2C7-BEA2-4910-A277-F1253F33780E}"
		   s:ds="{46DDC7A6-CDB6-43D2-A8F6-8562EB168933}"
		   s:id="{4F132C84-433D-44D2-8F53-EE6848FBF932}"
		   s:par="Reset Caching Options&amp;GridParameters&amp;icon=Alert&amp;FieldNames&amp;Styles=%7B1EC77492-81B5-44EC-89B1-6EABC53A412C%7D&amp;RenderingIdentifier&amp;DynamicPlaceholderId=1"
		   s:ph="headless-main"
		   s:ccb="Clear on publish">
			<rls>
				<ruleset>
					<rule uid="{7707F7BC-4968-4F14-AF9A-B7324FE28EC3}"
					      s:name="Specify name...">
						<conditions>
							<condition uid="004ACC37FDA2406EBAD85F216E19B569"
							           s:id="{9A4BEB4B-4B0F-4392-A798-124CEC8AADA4}"
							           s:rulesid="{DE078C90-9FF2-42BB-9D16-5E5DB1BCEEC4}"/>
						</conditions>
					</rule>
					<rule uid="{00000000-0000-0000-0000-000000000000}"
					      s:name="Default">
						<conditions>
							<condition uid="893E4C07442B4376BEED33C28F4CCC23"
							           s:id="{4888ABBB-F17D-4485-B14B-842413F88732}"/>
						</conditions>
						<actions/>
					</rule>
				</ruleset>
			</rls>
		</r>
	</d>
</r>
```

**Comment by b-rewired** [comment]
I'd love to know how you added the Rules field to the schema. Everything I've read about the Edge schema indicates it's hard coded and can't be (purposefully) modified.  Unless you create your own schema that mirrors the Edge one with your own customizations.  I'd rather not go that extra step.

**Comment by JackTheHack** [comment]
No changes to the schema.

I've just created new field of Rules type and would inherit items in Sitecore from that template.

Here is the template serialized 
https://github.com/JackTheHack/Sitecore.JSS-Rules-Engine-Sandbox/blob/master/src/items/templates/JSS%20Personalization/_PersonalizedPage/JSS%20Personalization/PersonalizationRules.yml

I've pushed a Sitecore sandbox repo here 
https://github.com/JackTheHack/Sitecore.JSS-Rules-Engine-Sandbox

**Comment by JackTheHack** [comment]
>It's all published and the raw Layout shows the correct xm

I just looked again at your code snippet and I can see you basically add rules to the layout personalization.

Unfortunately layout personalization is not accessible through Edge - it's indeed requires to extend the schema which I haven't look into.

Instead I have personalization rules in a separate custom `Rules` field and then I use it in JS to run personalization rules against.

**Comment by b-rewired** [comment]
Ok, now I get what you're doing. Food for thought for sure.  Thank you so very much for responding to my questions!
